# -*- coding: utf-8 -*-
"""geocoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KtP7QekFLQX_5OT7CATJP1T3iw_07xt1
"""

data.head()

from geopy.geocoders import Nominatim
response1 = requests.get("https://services6.arcgis.com/bdPqSfflsdgFRVVM/arcgis/rest/services/Weekly_Part_1_Crime_Offenses_2022/FeatureServer/0/query?where=1%3D1&outFields=DATEEND,DRNUMB,ADDRESS,CODE_DEFINED&outSR=4326&f=json")
data1 = response1.json()
data1 = pd.json_normalize(data1['features'],errors='ignore')

data1.rename(columns={
    'attributes.ADDRESS': 'Address'}, inplace=True)

for index, row in data1.iterrows():
  data1.loc[index,'Address'] = str.rstrip(data1.loc[index,'Address']) + " Syracuse"

for index1, row in data1.iterrows():
  tempstring = data1.loc[index1,'Address']
  tempstring = str(tempstring)
  try:
    geolocator1 = Nominatim(user_agent="Untitled"+str(index1)+".ipynb")
    location1 = geolocator1.geocode(tempstring, timeout = 10)
    print(location1)
    print(location1.address)
    print((location1.latitude, location1.longitude))
    data1['X'] = location1.latitude
    data1['Y'] = location1.longitude
  except AttributeError:
    data1['X'] = 0
    data1['Y'] = 0

from requests.api import head
import pandas as pd
import requests
import json
import folium
response = requests.get("https://services6.arcgis.com/bdPqSfflsdgFRVVM/arcgis/rest/services/Fire_Incidents/FeatureServer/0/query?where=1%3D1&outFields=propertyuse,compositeaddress,postalcode,X,Y,incidenttype,incidentnumber,alarmdate&outSR=4326&f=json")
response.status_code
data = response.json()
data = pd.json_normalize(data['features'],errors='ignore')

data.rename(columns={
    'attributes.compositeaddress': 'Address',
    'attributes.postalcode': 'ZIP code',
    'attributes.X': 'X',
    'attributes.Y': 'Y'}, inplace=True)

#response1 = requests.get("https://services6.arcgis.com/bdPqSfflsdgFRVVM/arcgis/rest/services/Weekly_Part_1_Crime_Offenses_2022/FeatureServer/0/query?where=1%3D1&outFields=DATEEND,DRNUMB,ADDRESS,CODE_DEFINED&outSR=4326&f=json")
#data1 = response1.json()
#data1 = pd.json_normalize(data1['features'],errors='ignore')

data1 = pd.read_pickle("crimedata.pkl")



map = folium.Map(location=[43.0493, -76.1455], zoom_start=12)
for index, row in data.iterrows():
  folium.CircleMarker([row['Y'], row['X']], radius=3, fill_color='red', fill_opacity=1, popup='Address: ' + str(row['Address'])).add_to(map)
for index2, row in data1.iterrows():
  if data1.loc[index2,'X'] == 0:
    continue
  folium.CircleMarker([row['X'], row['Y']], radius=3, fill_color='blue', fill_opacity=1, popup='Address: ' + str(row['Address'])).add_to(map)

map

"""# New Section"""

data1.to_pickle("crimedata.pkl")

from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="Untitled0.ipynb")
location = geolocator.geocode("100 CROLY ST Syracuse")
print(location.address)
print((location.latitude, location.longitude))

from geopy.geocoders import Nominatim
response1 = requests.get("https://services6.arcgis.com/bdPqSfflsdgFRVVM/arcgis/rest/services/Weekly_Part_1_Crime_Offenses_2022/FeatureServer/0/query?where=1%3D1&outFields=DATEEND,DRNUMB,ADDRESS,CODE_DEFINED&outSR=4326&f=json")
data1 = response1.json()
data1 = pd.json_normalize(data1['features'],errors='ignore')

data1.rename(columns={
    'attributes.ADDRESS': 'Address'}, inplace=True)

for index, row in data1.iterrows():
  data1.loc[index,'Address'] = str.rstrip(data1.loc[index,'Address']) + " Syracuse"

for index1, row in data1.iterrows():
  tempstring = data1.loc[index1,'Address']
  tempstring = str(tempstring)
  try:
    geolocator1 = Nominatim(user_agent="Untitled"+str(index1)+".ipynb")
    location1 = geolocator1.geocode(tempstring, timeout = 1)
    print(location1.address)
    print((location1.latitude, location1.longitude))
    data1.loc[index1,'X'] = location1.latitude
    data1.loc[index1,'Y'] = location1.longitude
    print(data1.loc[index1,'X'])
    print(data1.loc[index1,'Y'])
    print("")
  except AttributeError:
    data1.loc[index1,'X'] = 0
    data1[index1,'Y'] = 0
data1.to_pickle("crimedata.pkl")
data1.head()

data1.head()

from geopy.geocoders import Nominatim

response1 = requests.get("https://services6.arcgis.com/bdPqSfflsdgFRVVM/arcgis/rest/services/Weekly_Part_1_Crime_Offenses_2022/FeatureServer/0/query?where=1%3D1&outFields=DATEEND,DRNUMB,ADDRESS,CODE_DEFINED&outSR=4326&f=json")
data1 = response1.json()
data1 = pd.json_normalize(data1['features'],errors='ignore')
data1.rename(columns={
    'attributes.ADDRESS': 'Address'}, inplace=True)

for index, row in data1.iterrows():
  data1.loc[index,'Address'] = str.rstrip(data1.loc[index,'Address']) + " Syracuse"
tempstring = data1.loc[100,'Address']
geolocator = Nominatim(user_agent="Untitled0.ipynb")
location = geolocator.geocode(tempstring)
print(location.address)
print((location.latitude, location.longitude))

print(data1["Address"])

for index1, row in data1.iterrows():
  tempstring = data1.loc[index1,'Address']
  tempstring = str(tempstring)
  try:
    geolocator1 = Nominatim(user_agent="Untitled"+str(index1)+".ipynb")
    location1 = geolocator1.geocode(tempstring, timeout = 1)
    print(location1)
    print(location1.address)
    print((location1.latitude, location1.longitude))
    data1['X'] = location1.latitude
    data1['Y'] = location1.longitude
  except AttributeError:
    data1['X'] = 0
    data1['Y'] = 0